spring:
  config:
    import: "optional:application-secret.yml"

  datasource:
    url: jdbc:mysql://localhost:3306/mapmemo?serverTimezone=Asia/Seoul
    username: root
    password: 0000

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true